# Generated by Django 4.0.4 on 2022-07-22 14:16

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planName', models.CharField(choices=[('1Month', '1Month'), ('3Month', '3Month'), ('6Month', '6Month'), ('12Month', '12Month')], max_length=50, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainerList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainerName', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('trainerImage', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PackageList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packageName', models.CharField(choices=[('7 Day a Week', '7 Day a Week'), ('3 Day a Week', '3 Day a week')], max_length=50, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('plan', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='fitnessClub.planlist')),
            ],
        ),
        migrations.CreateModel(
            name='MemberList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('memberImage', models.ImageField(upload_to='')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=50, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitnessClub.packagelist')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitnessClub.planlist')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitnessClub.trainerlist')),
            ],
        ),
    ]
